In [21]:
with open("full2_test.out","rb") as f:
    data = f.read()

In [22]:
len(data) /8

195

In [23]:
%pylab
from struct import unpack
fmt = "%iL" % (len(data)/8)
a = unpack(fmt,data)

t0=np.array(a[::3])[:-1]
t1=np.array(a[1::3])[:-1]
t2=np.array(a[2::3])[1:]

del a

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


In [16]:
hist((t1-t0)/1e3,bins=50) # microseconds

(array([  1.29600000e+03,   4.10000000e+01,   4.20000000e+01,
          3.00000000e+01,   1.00000000e+01,   9.00000000e+00,
          7.00000000e+00,   1.00000000e+01,   5.00000000e+00,
          4.00000000e+00,   4.00000000e+00,   7.00000000e+00,
          1.00000000e+00,   2.00000000e+00,   4.00000000e+00,
          1.00000000e+00,   3.00000000e+00,   2.00000000e+00,
          2.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
        

In [9]:
hist((t1-t0)/1e3,bins=50) # microseconds

(array([ 13.,   6.,   8.,   2.,   5.,   7.,   0.,   0.,   0.,   0.,   0.,
          1.,  13.,  16.,  10.,  17.,  15.,   9.,   3.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   6.,   6.,   0.,   0.,   0.,   6.,   1.,
          5.,   4.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          8.,   9.,   5.,   0.,   4.,   7.]),
 array([  4.25968993e+10,   4.25974914e+10,   4.25980835e+10,
          4.25986756e+10,   4.25992677e+10,   4.25998598e+10,
          4.26004519e+10,   4.26010441e+10,   4.26016362e+10,
          4.26022283e+10,   4.26028204e+10,   4.26034125e+10,
          4.26040046e+10,   4.26045967e+10,   4.26051888e+10,
          4.26057809e+10,   4.26063731e+10,   4.26069652e+10,
          4.26075573e+10,   4.26081494e+10,   4.26087415e+10,
          4.26093336e+10,   4.26099257e+10,   4.26105178e+10,
          4.26111100e+10,   4.26117021e+10,   4.26122942e+10,
          4.26128863e+10,   4.26134784e+10,   4.26140705e+10,
          4.26146626e+10,   4.26152547

In [25]:
hist((t2-t1)/1e3,bins=500) # microseconds

(array([ 2.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.,  2.,  2.,  2.,  3.,
         2.,  0.,  3.,  2.,  1.,  4.,  3.,  1.,  3.,  3.,  2.,  3.,  5.,
         3.,  1.,  3.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [12]:
plot(t0)